### PR TITLE
Add a way to check if struct has any content

### PR DESCRIPTION
**Pull request by mpraglowski**

### CODE REVIEW

**Comment by obrok** [comment]
Sorry for not responding earlier, I didn't have this repo watched for some reason, I'll take a look tonight.

**Comment by mpraglowski** [comment]
no problem ;) please also check this one https://github.com/obrok/closed_struct/pull/2 - currently rspec is failing on travis because test code is outdated

**Comment by obrok** [comment]
@mpraglowski if you merge master CI should pass and I can merge

**Comment by mpraglowski** [comment]
@obrok done

**Comment by obrok** [comment]
Released, have fun

**Pull request merged**
